// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpJJd0lM9JFktkWMfiSDW-iKx4jLYMSbM',
    appId: '1:70365746998:web:509f76f007dee744920597',
    messagingSenderId: '70365746998',
    projectId: 'eventra-1eb59',
    authDomain: 'eventra-1eb59.firebaseapp.com',
    storageBucket: 'eventra-1eb59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCXqOO8O3Q2EbjL5I7sz4oPNFQA5ttgs',
    appId: '1:70365746998:android:a399e5d2fc1844d8920597',
    messagingSenderId: '70365746998',
    projectId: 'eventra-1eb59',
    storageBucket: 'eventra-1eb59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8JQc3qfU9azqH9z-0H1hNiadxSXl56Q',
    appId: '1:70365746998:ios:ece4ca9389ec574c920597',
    messagingSenderId: '70365746998',
    projectId: 'eventra-1eb59',
    storageBucket: 'eventra-1eb59.firebasestorage.app',
    androidClientId: '70365746998-k542f2e2vlrtvap6cdglmc7oukkv9l86.apps.googleusercontent.com',
    iosClientId: '70365746998-n84e4bpee2ok1j6i6r1rnhbuq8vpiu1e.apps.googleusercontent.com',
    iosBundleId: 'com.jimmy.eventra',
  );
}
